[[AlgRemez]]
arch = "aarch64"
git-tree-sha1 = "e961798f43730a9c01a27b09ac00f8ea3edac3ad"
os = "macos"

    [[AlgRemez.download]]
    sha256 = "925f5b3ea9a79a8d25746917fc1a7b32269d41aeae6e33cd72135852ad4495fe"
    url = "https://github.com/JuliaBinaryWrappers/AlgRemez_jll.jl/releases/download/AlgRemez-v0.1.1+0/AlgRemez.v0.1.1.aarch64-apple-darwin.tar.gz"
[[AlgRemez]]
arch = "aarch64"
git-tree-sha1 = "4fbc865329c018e4b36da61cf012eb5f97245291"
libc = "glibc"
os = "linux"

    [[AlgRemez.download]]
    sha256 = "9127385c790c826f6a0adff090982c0d464fdb9821d2217b7fdd95aee0a880e4"
    url = "https://github.com/JuliaBinaryWrappers/AlgRemez_jll.jl/releases/download/AlgRemez-v0.1.1+0/AlgRemez.v0.1.1.aarch64-linux-gnu.tar.gz"
[[AlgRemez]]
arch = "aarch64"
git-tree-sha1 = "70543c235dd54bad4d2d1df86bbb5d5108e62d72"
libc = "musl"
os = "linux"

    [[AlgRemez.download]]
    sha256 = "f6a3224089edfc9c5d606158866683d7cac565ca5fd4f0c0af0fe809aab249b9"
    url = "https://github.com/JuliaBinaryWrappers/AlgRemez_jll.jl/releases/download/AlgRemez-v0.1.1+0/AlgRemez.v0.1.1.aarch64-linux-musl.tar.gz"
[[AlgRemez]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "22a9f04568eaf06f61dd265d8699e743cbc390a4"
libc = "glibc"
os = "linux"

    [[AlgRemez.download]]
    sha256 = "3cd2dcd6c5607d12f087f8306f5fe4731919e8fb289d0f0ee8266b356ed8fc82"
    url = "https://github.com/JuliaBinaryWrappers/AlgRemez_jll.jl/releases/download/AlgRemez-v0.1.1+0/AlgRemez.v0.1.1.armv6l-linux-gnueabihf.tar.gz"
[[AlgRemez]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6cabdd10eb10a307fef38d25a7cc8484dfd77d27"
libc = "musl"
os = "linux"

    [[AlgRemez.download]]
    sha256 = "028ca09def6ddeeafbaf0f58932bd354c87d7efd5d60c44d308e3d152b820cba"
    url = "https://github.com/JuliaBinaryWrappers/AlgRemez_jll.jl/releases/download/AlgRemez-v0.1.1+0/AlgRemez.v0.1.1.armv6l-linux-musleabihf.tar.gz"
[[AlgRemez]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1d9020ef7dd779e09d86197772eea1c155d0c00f"
libc = "glibc"
os = "linux"

    [[AlgRemez.download]]
    sha256 = "42015965827130f96bddaf25266a92164aec3aa91b0e784b9f06d9d378792f45"
    url = "https://github.com/JuliaBinaryWrappers/AlgRemez_jll.jl/releases/download/AlgRemez-v0.1.1+0/AlgRemez.v0.1.1.armv7l-linux-gnueabihf.tar.gz"
[[AlgRemez]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "afc2a103256dc5ab0ad11c15b41ce88ce6feb351"
libc = "musl"
os = "linux"

    [[AlgRemez.download]]
    sha256 = "613c45c8b3200cb32fb85e3393de978f245f896e98f8fc645c72a7916f7e1af2"
    url = "https://github.com/JuliaBinaryWrappers/AlgRemez_jll.jl/releases/download/AlgRemez-v0.1.1+0/AlgRemez.v0.1.1.armv7l-linux-musleabihf.tar.gz"
[[AlgRemez]]
arch = "i686"
git-tree-sha1 = "3f9cd451403223917ccb2081d4c57cd1050348e1"
libc = "glibc"
os = "linux"

    [[AlgRemez.download]]
    sha256 = "2889c7e03bea9257c92f149af8b28dffbf99d6297de14e70b2d994a2009aa69d"
    url = "https://github.com/JuliaBinaryWrappers/AlgRemez_jll.jl/releases/download/AlgRemez-v0.1.1+0/AlgRemez.v0.1.1.i686-linux-gnu.tar.gz"
[[AlgRemez]]
arch = "i686"
git-tree-sha1 = "108cde73c6a3f59b1d500ed980375e6047687347"
libc = "musl"
os = "linux"

    [[AlgRemez.download]]
    sha256 = "3d7c1d11069beabe76e483567d19d7fa82443a0d93f439de305e8fb4f7fed130"
    url = "https://github.com/JuliaBinaryWrappers/AlgRemez_jll.jl/releases/download/AlgRemez-v0.1.1+0/AlgRemez.v0.1.1.i686-linux-musl.tar.gz"
[[AlgRemez]]
arch = "i686"
git-tree-sha1 = "1912ac8246f5bb7cb448398fa64e2a1eb641a76e"
os = "windows"

    [[AlgRemez.download]]
    sha256 = "0e9156355d28a3fb1d62a87caf1f1b35287bddd64d6d555fbd99c3f274026de8"
    url = "https://github.com/JuliaBinaryWrappers/AlgRemez_jll.jl/releases/download/AlgRemez-v0.1.1+0/AlgRemez.v0.1.1.i686-w64-mingw32.tar.gz"
[[AlgRemez]]
arch = "powerpc64le"
git-tree-sha1 = "3c2c63e794ca22b86a0e9b9e2aed070e72d5be40"
libc = "glibc"
os = "linux"

    [[AlgRemez.download]]
    sha256 = "833b8ffbe126a29232305829c7a54add3e54d84e779d527a07a6cddb70e7f63e"
    url = "https://github.com/JuliaBinaryWrappers/AlgRemez_jll.jl/releases/download/AlgRemez-v0.1.1+0/AlgRemez.v0.1.1.powerpc64le-linux-gnu.tar.gz"
[[AlgRemez]]
arch = "x86_64"
git-tree-sha1 = "0da93842f30cb29e4653d057b20cb687f8f51c5e"
os = "macos"

    [[AlgRemez.download]]
    sha256 = "eab10df8b58353a1eaf498f4c86d8b42a4f39b48c1b49a7c98f5058175aa3be3"
    url = "https://github.com/JuliaBinaryWrappers/AlgRemez_jll.jl/releases/download/AlgRemez-v0.1.1+0/AlgRemez.v0.1.1.x86_64-apple-darwin.tar.gz"
[[AlgRemez]]
arch = "x86_64"
git-tree-sha1 = "45afc7621996ff2b84579882488fe8e414b1ee79"
libc = "glibc"
os = "linux"

    [[AlgRemez.download]]
    sha256 = "60430805ccfc6819e194302b518f285f75d08d897d16bd82f0b28cd6e95fff8c"
    url = "https://github.com/JuliaBinaryWrappers/AlgRemez_jll.jl/releases/download/AlgRemez-v0.1.1+0/AlgRemez.v0.1.1.x86_64-linux-gnu.tar.gz"
[[AlgRemez]]
arch = "x86_64"
git-tree-sha1 = "db34c50a399d9590391b3cdd611c1b99cde3101f"
libc = "musl"
os = "linux"

    [[AlgRemez.download]]
    sha256 = "aee174098cc4a19a2639aa4d5f3962bd425da67e969bb2fca22f78d56b37183b"
    url = "https://github.com/JuliaBinaryWrappers/AlgRemez_jll.jl/releases/download/AlgRemez-v0.1.1+0/AlgRemez.v0.1.1.x86_64-linux-musl.tar.gz"
[[AlgRemez]]
arch = "x86_64"
git-tree-sha1 = "353e3d1b04062e3f40370648e25cd4448fe8cd62"
os = "freebsd"

    [[AlgRemez.download]]
    sha256 = "76b08f79734f9b2d74908aba703a74262cbf539a9d8175e90ad57cfb67ed5cc5"
    url = "https://github.com/JuliaBinaryWrappers/AlgRemez_jll.jl/releases/download/AlgRemez-v0.1.1+0/AlgRemez.v0.1.1.x86_64-unknown-freebsd.tar.gz"
[[AlgRemez]]
arch = "x86_64"
git-tree-sha1 = "648fd9cc409c59dac97791f91fb6a98ba96ade79"
os = "windows"

    [[AlgRemez.download]]
    sha256 = "8b20398be6867fdf851904eeb5a8e5bdd2c3995db07ef88b4a35d503a50df96c"
    url = "https://github.com/JuliaBinaryWrappers/AlgRemez_jll.jl/releases/download/AlgRemez-v0.1.1+0/AlgRemez.v0.1.1.x86_64-w64-mingw32.tar.gz"
