[[AlgRemez]]
arch = "aarch64"
git-tree-sha1 = "0a1b4bca96818825ca8505a45c5d11a7b43781ae"
libc = "glibc"
os = "linux"

    [[AlgRemez.download]]
    sha256 = "398ae5d8f2920835c7abf1d48f94a9d581c2c355b87dbd431639df6d107ff2b7"
    url = "https://github.com/JuliaBinaryWrappers/AlgRemez_jll.jl/releases/download/AlgRemez-v0.1.0+1/AlgRemez.v0.1.0.aarch64-linux-gnu.tar.gz"
[[AlgRemez]]
arch = "aarch64"
git-tree-sha1 = "e902af8db981e71757987d2c83bdb73ebbb20b2b"
libc = "musl"
os = "linux"

    [[AlgRemez.download]]
    sha256 = "b2c88b6ee2860529fb0c9da0f7e84c400ea33a19f440b17c62720d18e2b45a5b"
    url = "https://github.com/JuliaBinaryWrappers/AlgRemez_jll.jl/releases/download/AlgRemez-v0.1.0+1/AlgRemez.v0.1.0.aarch64-linux-musl.tar.gz"
[[AlgRemez]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3f48ec93b43ee7a05789efa5c60ffd8c61bf9cb0"
libc = "glibc"
os = "linux"

    [[AlgRemez.download]]
    sha256 = "268e8fd28bf7f009af3d533430f33c49ac90fde5d55e6a50fa8297b46772e368"
    url = "https://github.com/JuliaBinaryWrappers/AlgRemez_jll.jl/releases/download/AlgRemez-v0.1.0+1/AlgRemez.v0.1.0.armv7l-linux-gnueabihf.tar.gz"
[[AlgRemez]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "946081a6f016cd04e5a73abd002c73edbf9cb083"
libc = "musl"
os = "linux"

    [[AlgRemez.download]]
    sha256 = "6e353d4cb99d03821b3c1be88508f58ccb9715484e25254e3a835f73b2913d85"
    url = "https://github.com/JuliaBinaryWrappers/AlgRemez_jll.jl/releases/download/AlgRemez-v0.1.0+1/AlgRemez.v0.1.0.armv7l-linux-musleabihf.tar.gz"
[[AlgRemez]]
arch = "i686"
git-tree-sha1 = "af3675744c5446c33c062116c088fe558c03dfd6"
libc = "glibc"
os = "linux"

    [[AlgRemez.download]]
    sha256 = "ab90808c1b36a3b8dc83283c186f19473e5381007f71fa5d03f307e39e51cfaf"
    url = "https://github.com/JuliaBinaryWrappers/AlgRemez_jll.jl/releases/download/AlgRemez-v0.1.0+1/AlgRemez.v0.1.0.i686-linux-gnu.tar.gz"
[[AlgRemez]]
arch = "i686"
git-tree-sha1 = "7dab2a3c3ec0f63b435fa3df569230f2198a1321"
libc = "musl"
os = "linux"

    [[AlgRemez.download]]
    sha256 = "1e944b1939906a23a520daf6898369b47e93d7fb609bc88c6807125ac5a67d3a"
    url = "https://github.com/JuliaBinaryWrappers/AlgRemez_jll.jl/releases/download/AlgRemez-v0.1.0+1/AlgRemez.v0.1.0.i686-linux-musl.tar.gz"
[[AlgRemez]]
arch = "i686"
git-tree-sha1 = "ebbd80431edd688aec8292fefb0742cd56f0dcf3"
os = "windows"

    [[AlgRemez.download]]
    sha256 = "88bb3bb81d4aa51136f09cd98a08a1260fdd8c08e203b706949ea696b099b1f6"
    url = "https://github.com/JuliaBinaryWrappers/AlgRemez_jll.jl/releases/download/AlgRemez-v0.1.0+1/AlgRemez.v0.1.0.i686-w64-mingw32.tar.gz"
[[AlgRemez]]
arch = "powerpc64le"
git-tree-sha1 = "51856fbd359b0c8f37071df70c72905c5bb96f6b"
libc = "glibc"
os = "linux"

    [[AlgRemez.download]]
    sha256 = "10d4e4e339dd42aa617fe437b92a511dc997ef9c20a8e81c7a59b6c9c573dff6"
    url = "https://github.com/JuliaBinaryWrappers/AlgRemez_jll.jl/releases/download/AlgRemez-v0.1.0+1/AlgRemez.v0.1.0.powerpc64le-linux-gnu.tar.gz"
[[AlgRemez]]
arch = "x86_64"
git-tree-sha1 = "2d88c77250ba65dfb4b1abe316a74adfa52cdafc"
os = "macos"

    [[AlgRemez.download]]
    sha256 = "8ba3de00ebce52d26557f038422e3374d450e36351da0e1fb1668cbc3bc7b0b9"
    url = "https://github.com/JuliaBinaryWrappers/AlgRemez_jll.jl/releases/download/AlgRemez-v0.1.0+1/AlgRemez.v0.1.0.x86_64-apple-darwin.tar.gz"
[[AlgRemez]]
arch = "x86_64"
git-tree-sha1 = "92d46da4b5c3548613c37b4d2daaf916401bcd54"
libc = "glibc"
os = "linux"

    [[AlgRemez.download]]
    sha256 = "401678ee644e3af31b3b7fb5c9d42b80034dbc9aaa3a22263090352a81ec149a"
    url = "https://github.com/JuliaBinaryWrappers/AlgRemez_jll.jl/releases/download/AlgRemez-v0.1.0+1/AlgRemez.v0.1.0.x86_64-linux-gnu.tar.gz"
[[AlgRemez]]
arch = "x86_64"
git-tree-sha1 = "386cba3b83088571f2a5302a2e243c53cb70cb68"
libc = "musl"
os = "linux"

    [[AlgRemez.download]]
    sha256 = "bb7829491a29471360e9c48bb2611ba71cfa901584d9c4204e2fed53d11b0f78"
    url = "https://github.com/JuliaBinaryWrappers/AlgRemez_jll.jl/releases/download/AlgRemez-v0.1.0+1/AlgRemez.v0.1.0.x86_64-linux-musl.tar.gz"
[[AlgRemez]]
arch = "x86_64"
git-tree-sha1 = "c5eeb73cf07ccea6f23b10553983fa7dfc60ff61"
os = "freebsd"

    [[AlgRemez.download]]
    sha256 = "1ab9abe470b0f63c18af2a4d212292ecd6b2cbab9baaea9b634167476bf38b95"
    url = "https://github.com/JuliaBinaryWrappers/AlgRemez_jll.jl/releases/download/AlgRemez-v0.1.0+1/AlgRemez.v0.1.0.x86_64-unknown-freebsd.tar.gz"
[[AlgRemez]]
arch = "x86_64"
git-tree-sha1 = "467f89eb4e468d50c2084b50d2a80ae0503e97ef"
os = "windows"

    [[AlgRemez.download]]
    sha256 = "15a4aa7cd5d3da7218e759e3be219b502d2242cfd02d2d370b731c58f99b1a18"
    url = "https://github.com/JuliaBinaryWrappers/AlgRemez_jll.jl/releases/download/AlgRemez-v0.1.0+1/AlgRemez.v0.1.0.x86_64-w64-mingw32.tar.gz"
